import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting JB Physics database seed for all 35 PYQ questions...');

  // 1. Create Users
  const adminPassword = await bcrypt.hash('admin123physics', 10);
  const studentPassword = await bcrypt.hash('student123', 10);

  const admin = await prisma.user.upsert({
    where: { email: 'admin@jbphysics.com' },
    update: {},
    create: {
      name: 'JB Physics Creator',
      email: 'admin@jbphysics.com',
      passwordHash: adminPassword,
      role: 'ADMIN',
      streakCount: 5,
    },
  });

  const student = await prisma.user.upsert({
    where: { email: 'student@jbphysics.com' },
    update: {},
    create: {
      name: 'Rohan Banerjee',
      email: 'student@jbphysics.com',
      passwordHash: studentPassword,
      role: 'STUDENT',
      streakCount: 3,
    },
  });

  console.log('✅ Created users:', admin.email, student.email);

  // 2. Create Chapters
  const ch1 = await prisma.chapter.upsert({
    where: { slug: 'electrostatics' },
    update: {},
    create: {
      titleEn: 'Unit 1: Electrostatics',
      titleBn: 'অধ্যায় ১: স্থির তড়িৎ ও ক্ষেত্র',
      slug: 'electrostatics',
      descriptionEn: 'Electric charges, Coulomb law, electric fields, Gauss theorem, electric flux, electrostatic potential, and capacitors.',
      descriptionBn: 'তড়িৎ আধান, কুলম্বের সূত্র, তড়িৎক্ষেত্র, গাউসের উপপাদ্য, তড়িৎ ফ্লাক্স, স্থির-তড়িৎ বিভব এবং ধারক ও ধারকত্ব।',
      orderIndex: 1,
      icon: 'Atom',
      isPublished: true,
    },
  });

  const ch2 = await prisma.chapter.upsert({
    where: { slug: 'current-electricity' },
    update: {},
    create: {
      titleEn: 'Unit 2: Current Electricity',
      titleBn: 'অধ্যায় ২: প্রবাহী তড়িৎ',
      slug: 'current-electricity',
      descriptionEn: 'Electric current, drift velocity, Ohm law, resistivity, temperature dependence, Kirchhoff laws, potentiometer, and meters.',
      descriptionBn: 'তড়িৎপ্রবাহ, বিচলন বেগ, ওহমের সূত্র, রোধাঙ্ক, তাপমাত্রা নির্ভরতা, কার্শফের সূত্রাবলী, পোটেনশিওমিটার এবং মিটার।',
      orderIndex: 2,
      icon: 'Zap',
      isPublished: true,
    },
  });

  const ch3 = await prisma.chapter.upsert({
    where: { slug: 'magnetism' },
    update: {},
    create: {
      titleEn: 'Unit 3: Magnetic Effects of Current & Magnetism',
      titleBn: 'অধ্যায় ৩: তড়িৎপ্রবাহের চৌম্বক ক্রিয়া ও চুম্বকত্ব',
      slug: 'magnetism',
      descriptionEn: 'Biot-Savart law, Ampere circuital law, solenoid, Lorentz force, magnetic dipole, Earth magnetism, and magnetic materials.',
      descriptionBn: 'বায়ো-সাভার্ট সূত্র, অ্যাম্পিয়ারের সূত্র, সলিনয়েড, লরেঞ্জ বল, চৌম্বক দ্বিমেরু, ভূ-চুম্বকত্ব এবং চৌম্বক পদার্থ।',
      orderIndex: 3,
      icon: 'Compass',
      isPublished: true,
    },
  });

  const ch4 = await prisma.chapter.upsert({
    where: { slug: 'emi-ac' },
    update: {},
    create: {
      titleEn: 'Unit 4: Electromagnetic Induction & Alternating Current',
      titleBn: 'অধ্যায় ৪: তড়িৎচুম্বকীয় আবেশ ও পরিবর্তী প্রবাহ',
      slug: 'emi-ac',
      descriptionEn: 'Faraday law, Lenz law, mutual & self inductance, AC circuits, RMS & average values, LCR series resonance, and transformers.',
      descriptionBn: 'ফ্যারাডের সূত্র, লেঞ্জের সূত্র, স্বাবেশ ও পারস্পরিক আবেশ, ac বর্তনী, rms ও গড় মান, শ্রেণি LCR অনুনাদ এবং ট্রান্সফরমার।',
      orderIndex: 4,
      icon: 'Activity',
      isPublished: true,
    },
  });

  const ch5 = await prisma.chapter.upsert({
    where: { slug: 'em-waves' },
    update: {},
    create: {
      titleEn: 'Unit 5: Electromagnetic Waves',
      titleBn: 'অধ্যায় ৫: তড়িৎচুম্বকীয় তরঙ্গ',
      slug: 'em-waves',
      descriptionEn: 'Displacement current, EM wave characteristics, orthogonal E and B fields, speed in vacuum and medium, and EM spectrum.',
      descriptionBn: 'সরণ প্রবাহ, তড়িৎচুম্বকীয় তরঙ্গের বৈশিষ্ট্য, লম্ব E ও B ক্ষেত্র, শূন্যস্থান ও মাধ্যমে বেগ এবং বর্ণালী।',
      orderIndex: 5,
      icon: 'Radio',
      isPublished: true,
    },
  });

  console.log('✅ Created 5 Chapters');

  // 3. Complete 35 PYQ Questions
  const questionsData = [
    // --- Q1 ---
    {
      code: 'WB12-PYQ-Q001',
      chapterId: ch1.id,
      difficulty: 'MEDIUM',
      questionEn: 'The electric field in a region is $\\vec{E} = (3\\hat{i} - 4\\hat{j} + 2\\hat{k})\\text{ V/m}$. The electric flux passing through a square region of side $2\\text{ m}$ situated in the $YZ$-plane in that region is:',
      questionBn: 'কোনো অঞ্চলে ক্রিয়াশীল তড়িৎক্ষেত্র হল $\\vec{E} = (3\\hat{i} - 4\\hat{j} + 2\\hat{k})\\text{ V/m}$; ওই অঞ্চলে $YZ$-তলে অবস্থিত $2\\text{ m}$ বাহুবিশিষ্ট বর্গাকার ক্ষেত্রের মধ্য দিয়ে অতিক্রান্ত তড়িৎ ফ্লাক্স হল—',
      optionA_En: '$12\\text{ V}\\cdot\\text{m}$',
      optionA_Bn: '$12\\text{ V}\\cdot\\text{m}$',
      optionB_En: '$6\\text{ V}\\cdot\\text{m}$',
      optionB_Bn: '$6\\text{ V}\\cdot\\text{m}$',
      optionC_En: '$-16\\text{ V}\\cdot\\text{m}$',
      optionC_Bn: '$-16\\text{ V}\\cdot\\text{m}$',
      optionD_En: '$8\\text{ V}\\cdot\\text{m}$',
      optionD_Bn: '$8\\text{ V}\\cdot\\text{m}$',
      correctOption: 'A',
      explanationEn: 'For a planar square in the $YZ$-plane, its area normal vector points perpendicular to the plane along the $+X$ axis: $\\vec{A} = (\\text{side})^2 \\hat{i} = (2 \\times 2)\\hat{i} = 4\\hat{i}\\text{ m}^2$.\n\nElectric flux is the scalar dot product:\n$$\\Phi = \\vec{E} \\cdot \\vec{A} = (3\\hat{i} - 4\\hat{j} + 2\\hat{k}) \\cdot 4\\hat{i} = (3 \\times 4) + 0 + 0 = 12\\text{ V}\\cdot\\text{m}$$\nNotice that the $Y$ and $Z$ components of the electric field graze parallel to the surface without crossing it!',
      explanationBn: '$YZ$-তলে অবস্থিত বর্গাকার ক্ষেত্রের ক্ষেত্রফল ভেক্টর $\\vec{A}$ তলের সঙ্গে লম্বভাবে $+X$ অক্ষ বরাবর ক্রিয়াশীল: $\\vec{A} = (\\text{বাহু})^2 \\hat{i} = (2 \\times 2)\\hat{i} = 4\\hat{i}\\text{ m}^2$।\n\nতড়িৎ ফ্লাক্স হল স্কেলার ডট গুণফল:\n$$\\Phi = \\vec{E} \\cdot \\vec{A} = (3\\hat{i} - 4\\hat{j} + 2\\hat{k}) \\cdot 4\\hat{i} = 3 \\times 4 = 12\\text{ V}\\cdot\\text{m}$$',
      formula: '\\Phi = \\vec{E} \\cdot \\vec{A}',
      simulationType: 'ELECTRIC_FLUX_3D',
      simulationParams: JSON.stringify({ fieldVector: [3, -4, 2], plane: 'YZ', side: 2 }),
      isQuestionOfDay: true,
      isPublished: true,
    },
    // --- Q2 ---
    {
      code: 'WB12-PYQ-Q002',
      chapterId: ch1.id,
      difficulty: 'MEDIUM',
      questionEn: 'The dielectric constant of the medium between the plates of a parallel plate capacitor is $2$. Its capacitance is $3\\,\\mu\\text{F}$. Now, the distance between the plates is doubled and a plate of dielectric constant $k = 4$ is inserted into that space. Now the capacitance of the capacitor will be:',
      questionBn: 'একটি সমান্তরাল পাতধারকের পাতদ্বয়ের মধ্যবর্তী মাধ্যমের পরাবৈদ্যুতিক ধ্রুবক $2$। এর ধারকত্ব $3\\,\\mu\\text{F}$। এখন, ধারকটির পাতদ্বয়ের মধ্যবর্তী দূরত্ব দ্বিগুণ করে, ওই ফাঁকা স্থানে $k = 4$ পরাবৈদ্যুতিক ধ্রুবকসম্পন্ন প্লেট প্রবেশ করানো হল। এখন ধারকটির ধারকত্ব হবে—',
      optionA_En: '$1\\,\\mu\\text{F}$',
      optionA_Bn: '$1\\,\\mu\\text{F}$',
      optionB_En: '$2\\,\\mu\\text{F}$',
      optionB_Bn: '$2\\,\\mu\\text{F}$',
      optionC_En: '$6\\,\\mu\\text{F}$',
      optionC_Bn: '$6\\,\\mu\\text{F}$',
      optionD_En: '$9\\,\\mu\\text{F}$',
      optionD_Bn: '$9\\,\\mu\\text{F}$',
      correctOption: 'B',
      explanationEn: 'Initially, capacitance of thickness $d$ with dielectric $k_1 = 2$ is $C_1 = \\frac{2\\varepsilon_0 A}{d} = 3\\,\\mu\\text{F}$.\nWhen distance is doubled to $2d$, a dielectric slab of thickness $d$ and $k_2 = 4$ is inserted in the new space.\nThis forms a series combination of two capacitors:\n- $C_1 = 3\\,\\mu\\text{F}$ (thickness $d$, $k_1 = 2$)\n- $C_2 = \\frac{4\\varepsilon_0 A}{d} = 2 \\times C_1 = 6\\,\\mu\\text{F}$ (thickness $d$, $k_2 = 4$)\n\nEquivalent series capacitance:\n$$C_{\\text{eq}} = \\frac{C_1 C_2}{C_1 + C_2} = \\frac{3 \\times 6}{3 + 6} = \\frac{18}{9} = 2\\,\\mu\\text{F}$$',
      explanationBn: 'প্রাথমিকভাবে $d$ ব্যবধানে $k_1 = 2$ মাধ্যমের জন্য $C_1 = \\frac{2\\varepsilon_0 A}{d} = 3\\,\\mu\\text{F}$।\nব্যবধান দ্বিগুণ ($2d$) করে নতুন ফাঁকা স্থানে $k_2 = 4$ ধ্রুবকযুক্ত $d$ বেধের প্লেট দিলে দুটি ধারক শ্রেণিতে যুক্ত হয়:\n- প্রথম ধারক $C_1 = 3\\,\\mu\\text{F}$\n- দ্বিতীয় ধারক $C_2 = \\frac{4\\varepsilon_0 A}{d} = 6\\,\\mu\\text{F}$\n\nশ্রেণি সমবায়ে তুল্য ধারকত্ব:\n$$C_{\\text{eq}} = \\frac{3 \\times 6}{3 + 6} = 2\\,\\mu\\text{F}$$',
      formula: 'C_{\\text{eq}} = \\frac{C_1 C_2}{C_1 + C_2}',
      simulationType: 'CAPACITOR_DIELECTRIC',
      simulationParams: JSON.stringify({ initialDielectric: 2, finalDielectric: 4 }),
      isPublished: true,
    },
    // --- Q3 ---
    {
      code: 'WB12-PYQ-Q003',
      chapterId: ch1.id,
      difficulty: 'HARD',
      questionEn: 'Two conductors $X$ and $Y$ have capacitances $3C$ and $C$ respectively. A charge $Q$ is given to conductor $X$, which is then shared with conductor $Y$. The ratio of total energy after sharing to total initial energy will be:',
      questionBn: 'দুটি পরিবাহী $X$ এবং $Y$-এর ধারকত্ব যথাক্রমে $3C$ এবং $C$। পরিবাহী $X$-এ $Q$ আধান দেওয়া হল যা পরিবাহীটি $Y$-এর সঙ্গে ভাগ করে নেয়। ভাগ হওয়ার পরে মোট শক্তি এবং মোট প্রাথমিক শক্তির অনুপাত হবে—',
      optionA_En: '$9:16$',
      optionA_Bn: '$9:16$',
      optionB_En: '$\\sqrt{3}:2$',
      optionB_Bn: '$\\sqrt{3}:2$',
      optionC_En: '$3:4$',
      optionC_Bn: '$3:4$',
      optionD_En: '$4:3$',
      optionD_Bn: '$4:3$',
      correctOption: 'C',
      explanationEn: 'Initial electrostatic energy stored in $X$: $U_i = \\frac{Q^2}{2(3C)} = \\frac{Q^2}{6C}$.\n\nWhen connected, total capacitance is $C_{\\text{total}} = 3C + C = 4C$, and charge $Q$ is conserved.\nFinal energy: $U_f = \\frac{Q^2}{2(4C)} = \\frac{Q^2}{8C}$.\n\nRatio:\n$$\\frac{U_f}{U_i} = \\frac{Q^2/8C}{Q^2/6C} = \\frac{6}{8} = \\frac{3}{4} = 3:4$$',
      explanationBn: 'প্রাথমিক শক্তি: $U_i = \\frac{Q^2}{2(3C)} = \\frac{Q^2}{6C}$।\nসংযুক্ত করার পর মোট ধারকত্ব $C_{\\text{total}} = 4C$।\nচূড়ান্ত মোট শক্তি: $U_f = \\frac{Q^2}{2(4C)} = \\frac{Q^2}{8C}$।\nঅনুপাত: $\\frac{U_f}{U_i} = \\frac{6}{8} = \\frac{3}{4}$।',
      formula: 'U = \\frac{Q^2}{2C}',
      simulationType: 'CAPACITOR_DIELECTRIC',
      isPublished: true,
    },
    // --- Q4 ---
    {
      code: 'WB12-PYQ-Q004',
      chapterId: ch2.id,
      difficulty: 'MEDIUM',
      questionEn: 'A potential difference $V$ is applied across the ends of a conductor of length $l$ and cross-sectional area $A$.\nStatement I: If $V$ is doubled, current density will be doubled.\nStatement II: If $V$ is doubled, drift velocity will become half.\nStatement III: If $A$ is doubled, current density will decrease.\nWhich statement(s) is/are correct?',
      questionBn: '$l$ দৈর্ঘ্যবিশিষ্ট ও $A$ প্রস্থচ্ছেদবিশিষ্ট কোনো পরিবাহীর দু-প্রান্তে $V$ বিভবপ্রভেদ প্রয়োগ করা হল।\nবিবৃতি I: বিভবপ্রভেদ দ্বিগুণ করা হলে তড়িৎপ্রবাহ ঘনত্ব দ্বিগুণ হবে।\nবিবৃতি II: বিভবপ্রভেদ দ্বিগুণ করা হলে বিচলন বেগ অর্ধেক হয়ে যাবে।\nবিবৃতি III: প্রস্থচ্ছেদ দ্বিগুণ করা হলে তড়িৎপ্রবাহ ঘনত্ব কমে যাবে।\nকোন বিবৃতিটি সঠিক?',
      optionA_En: 'I and II are correct',
      optionA_Bn: 'I এবং II সঠিক',
      optionB_En: 'Only I is correct',
      optionB_Bn: 'কেবলমাত্র I সঠিক',
      optionC_En: 'Only III is correct',
      optionC_Bn: 'কেবলমাত্র III সঠিক',
      optionD_En: 'II and III are correct',
      optionD_Bn: 'II এবং III সঠিক',
      correctOption: 'B',
      explanationEn: 'Current density $j = \\sigma E = \\sigma \\frac{V}{l}$.\n- Since $j \\propto V$, doubling $V$ doubles $j$. (Statement I is TRUE)\n- Drift velocity $v_d = \\mu E = \\mu \\frac{V}{l} \\propto V$, so doubling $V$ doubles $v_d$, not halves. (Statement II is FALSE)\n- Current density $j = \\sigma V/l$ does not depend on area $A$ for fixed voltage and length. (Statement III is FALSE)\nThus, only Statement I is correct.',
      explanationBn: 'প্রবাহ ঘনত্ব $j = \\sigma \\frac{V}{l}$।\n- $j \\propto V$ হওয়ায় বিভব দ্বিগুণ করলে প্রবাহ ঘনত্ব দ্বিগুণ হবে (বিবৃতি I সঠিক)।\n- বিচলন বেগ $v_d \\propto V$ হওয়ায় বিভব দ্বিগুণ করলে বেগ দ্বিগুণ হবে, অর্ধেক নয় (বিবৃতি II ভুল)।\n- প্রবাহ ঘনত্ব ক্ষেত্রফল $A$-এর উপর নির্ভর করে না (বিবৃতি III ভুল)।',
      formula: 'j = \\sigma \\frac{V}{l}',
      simulationType: 'DRIFT_AND_RESISTANCE',
      simulationParams: JSON.stringify({ mode: 'DRIFT' }),
      isPublished: true,
    },
    // --- Q5 ---
    {
      code: 'WB12-PYQ-Q005',
      chapterId: ch2.id,
      difficulty: 'EASY',
      questionEn: 'Let the resistance of a wire of length $l$ be $R$. The wire is stretched uniformly until its length becomes $x$ times the initial length. The new resistance of the wire will be:',
      questionBn: 'ধরা যাক $l$ দৈর্ঘ্যবিশিষ্ট একটি তারের রোধ হল $R$। এখন তারটিকে ততক্ষণ টানা হল যতক্ষণ না তারটির দৈর্ঘ্য পূর্বের $x$ গুণ হয়। এখন তারটির রোধ হবে—',
      optionA_En: '$x^2 R$',
      optionA_Bn: '$x^2 R$',
      optionB_En: '$x R$',
      optionB_Bn: '$x R$',
      optionC_En: '$\\dfrac{R}{x}$',
      optionC_Bn: '$\\dfrac{R}{x}$',
      optionD_En: '$R$',
      optionD_Bn: '$R$',
      correctOption: 'A',
      explanationEn: 'When stretched uniformly, the volume $V = A \\cdot l$ remains constant. When $l\' = x l$, the area becomes $A\' = A / x$.\n\nNew resistance:\n$$R\' = \\rho \\frac{l\'}{A\'} = \\rho \\frac{x l}{A / x} = x^2 \\left(\\rho \\frac{l}{A}\\right) = x^2 R$$',
      explanationBn: 'তার টানলে আয়তন ধ্রুবক থাকে ($A\' = A/x$)।\nনতুন রোধ:\n$$R\' = \\rho \\frac{x l}{A/x} = x^2 \\left(\\rho \\frac{l}{A}\\right) = x^2 R$$',
      formula: 'R\' = x^2 R',
      simulationType: 'DRIFT_AND_RESISTANCE',
      simulationParams: JSON.stringify({ mode: 'STRETCH' }),
      isPublished: true,
    },
    // --- Q6 ---
    {
      code: 'WB12-PYQ-Q006',
      chapterId: ch3.id,
      difficulty: 'EASY',
      questionEn: "According to Ampere's circuital law, for an ideal long solenoid, the magnetic field strength $B$ on its axis and its radius $r$ are related as:",
      questionBn: 'অ্যাম্পিয়ারের বর্তনী সূত্র অনুযায়ী একটি আদর্শ সলিনয়েডের অক্ষে চৌম্বক ক্ষেত্রপ্রাবল্য $B$ এবং এর ব্যাসার্ধ $r$ হলে—',
      optionA_En: '$B \\propto r$',
      optionA_Bn: '$B \\propto r$',
      optionB_En: '$B \\propto \\dfrac{1}{r}$',
      optionB_Bn: '$B \\propto \\dfrac{1}{r}$',
      optionC_En: '$B \\propto \\dfrac{1}{r^2}$',
      optionC_Bn: '$B \\propto \\dfrac{1}{r^2}$',
      optionD_En: '$B$ is independent of $r$',
      optionD_Bn: '$B$, $r$-এর নিরপেক্ষ',
      correctOption: 'D',
      explanationEn: 'The magnetic field inside an ideal solenoid is uniform and given by $B = \\mu_0 n I$, where $n$ is the number of turns per unit length and $I$ is the current. It is completely independent of the radius $r$.',
      explanationBn: 'আদর্শ সলিনয়েডের অক্ষ বরাবর চৌম্বক ক্ষেত্র $B = \\mu_0 n I$। এই মান সলিনয়েডের ব্যাসার্ধ $r$-এর উপর নির্ভর করে না ($B$, $r$-এর নিরপেক্ষ)।',
      formula: 'B = \\mu_0 n I',
      simulationType: 'MAGNETIC_FIELD_CURRENTS',
      simulationParams: JSON.stringify({ mode: 'SOLENOID' }),
      isPublished: true,
    },
    // --- Q7 ---
    {
      code: 'WB12-PYQ-Q007',
      chapterId: ch2.id,
      difficulty: 'MEDIUM',
      questionEn: 'The resistance of a voltmeter is $300\\,\\Omega$. The instrument can measure a maximum potential difference of $150\\text{ V}$. To convert this instrument into an ammeter capable of measuring currents up to $8\\text{ A}$, the resistance to be connected is:',
      questionBn: 'একটি ভোল্টমিটারের রোধ $300\\,\\Omega$। যন্ত্রটি $150\\text{ V}$ সর্বোচ্চ বিভবপার্থক্য পরিমাপ করতে পারে। যন্ত্রটিকে $8\\text{ A}$ পর্যন্ত প্রবাহমাত্রা মাপার উপযুক্ত অ্যামিটারে পরিণত করতে হলে যে রোধ যুক্ত করতে হবে, তা হল—',
      optionA_En: '$20\\,\\Omega$, in parallel',
      optionA_Bn: '$20\\,\\Omega$, সমান্তরালে',
      optionB_En: '$20\\,\\Omega$, in series',
      optionB_Bn: '$20\\,\\Omega$, শ্রেণিতে',
      optionC_En: '$30\\,\\Omega$, in parallel',
      optionC_Bn: '$30\\,\\Omega$, সমান্তরালে',
      optionD_En: '$40\\,\\Omega$, in series',
      optionD_Bn: '$40\\,\\Omega$, শ্রেণিতে',
      correctOption: 'A',
      explanationEn: 'Full scale deflection current of the voltmeter coil:\n$$I_g = \\frac{V_g}{R_g} = \\frac{150\\text{ V}}{300\\,\\Omega} = 0.5\\text{ A}$$\nTo convert into an ammeter measuring $I = 8\\text{ A}$, connect shunt $S$ in parallel:\n$$S = \\frac{I_g R_g}{I - I_g} = \\frac{0.5 \\times 300}{8 - 0.5} = \\frac{150}{7.5} = 20\\,\\Omega\\text{ in parallel}$$',
      explanationBn: 'ভোল্টমিটারের সর্বোচ্চ প্রবাহ $I_g = \\frac{150}{300} = 0.5\\text{ A}$।\n$8\\text{ A}$ প্রবাহের অ্যামিটারে রূপান্তর করতে সমান্তরালে শান্ট $S$ যুক্ত করতে হয়:\n$$S = \\frac{I_g R_g}{I - I_g} = \\frac{0.5 \\times 300}{8 - 0.5} = 20\\,\\Omega\\text{ সমান্তরালে}$$',
      formula: 'S = \\frac{I_g R_g}{I - I_g}',
      simulationType: 'CIRCUIT_INSTRUMENTS',
      simulationParams: JSON.stringify({ mode: 'AMMETER_SHUNT' }),
      isPublished: true,
    },
    // --- Q8 ---
    {
      code: 'WB12-PYQ-Q008',
      chapterId: ch3.id,
      difficulty: 'MEDIUM',
      questionEn: 'For the semicircular conductor of radius $a$ carrying current $i$ connected to collinear straight leads: the magnetic field at the center $O$ of the conductor will be:',
      questionBn: 'অর্ধবৃত্তাকার পরিবাহীর ক্ষেত্রে (চিত্রে দেখানো হয়েছে): পরিবাহীর কেন্দ্রবিন্দুতে চৌম্বক ক্ষেত্র হবে—',
      optionA_En: '$\\dfrac{\\mu_0 i}{2a}$',
      optionA_Bn: '$\\dfrac{\\mu_0 i}{2a}$',
      optionB_En: '$\\dfrac{\\mu_0 i}{2\\pi a}$',
      optionB_Bn: '$\\dfrac{\\mu_0 i}{2\\pi a}$',
      optionC_En: 'Zero',
      optionC_Bn: 'শূন্য',
      optionD_En: '$\\dfrac{\\mu_0 i}{4a}$',
      optionD_Bn: '$\\dfrac{\\mu_0 i}{4a}$',
      correctOption: 'D',
      explanationEn: 'The magnetic field at the center of a full circular loop is $B = \\frac{\\mu_0 i}{2a}$. For a semicircle, it is exactly half:\n$$B_{\\text{semi}} = \\frac{1}{2}\\left(\\frac{\\mu_0 i}{2a}\\right) = \\frac{\\mu_0 i}{4a}$$\nThe straight wires lie along lines passing through $O$, so by Biot-Savart law ($\\sin 0^\\circ = 0$) their magnetic field at $O$ is zero.',
      explanationBn: 'বৃত্তাকার তারের কেন্দ্রে চৌম্বক ক্ষেত্র $B = \\frac{\\mu_0 i}{2a}$। অর্ধবৃত্তের জন্য:\n$$B_{\\text{semi}} = \\frac{1}{2}\\left(\\frac{\\mu_0 i}{2a}\\right) = \\frac{\\mu_0 i}{4a}$$\nসোজা তারগুলি কেন্দ্র $O$-এর সরলরেখায় অবস্থিত হওয়ায় তাদের অবদান শূন্য।',
      formula: 'B = \\frac{\\mu_0 i}{4a}',
      simulationType: 'MAGNETIC_FIELD_CURRENTS',
      simulationParams: JSON.stringify({ mode: 'SEMICIRCLE' }),
      isPublished: true,
    },
    // --- Q9 ---
    {
      code: 'WB12-PYQ-Q009',
      chapterId: ch3.id,
      difficulty: 'EASY',
      questionEn: "At a certain place, the vertical component of Earth's magnetic field is twice the horizontal component ($B_v = 2 B_h$). If the angle of dip at that place is $\\theta$, the value of $\\tan\\theta$ will be:",
      questionBn: 'কোনো একস্থানে পৃথিবীর চৌম্বক ক্ষেত্রের উল্লম্ব উপাংশ অনুভূমিক উপাংশের দ্বিগুণ। ওই স্থানে বিনতি কোণ $\\theta$ হলে, $\\tan\\theta$-এর মান হবে—',
      optionA_En: '$2$',
      optionA_Bn: '$2$',
      optionB_En: '$\\dfrac{1}{2}$',
      optionB_Bn: '$\\dfrac{1}{2}$',
      optionC_En: '$\\dfrac{1}{\\sqrt{3}}$',
      optionC_Bn: '$\\dfrac{1}{\\sqrt{3}}$',
      optionD_En: '$\\sqrt{3}$',
      optionD_Bn: '$\\sqrt{3}$',
      correctOption: 'A',
      explanationEn: 'The angle of dip $\\theta$ relates vertical and horizontal components by $\\tan\\theta = \\frac{B_v}{B_h}$.\nGiven $B_v = 2 B_h$:\n$$\\tan\\theta = \\frac{2 B_h}{B_h} = 2$$',
      explanationBn: 'বিনতি কোণ $\\theta$-এর সূত্র: $\\tan\\theta = \\frac{B_v}{B_h}$।\nযেহেতু $B_v = 2 B_h$, তাই $\\tan\\theta = \\frac{2 B_h}{B_h} = 2$।',
      formula: '\\tan\\theta = \\frac{B_v}{B_h}',
      simulationType: 'EARTH_MAGNETISM_DIPOLE',
      simulationParams: JSON.stringify({ mode: 'DIP_CIRCLE', bvRatio: 2.0 }),
      isPublished: true,
    },
    // --- Q10 ---
    {
      code: 'WB12-PYQ-Q010',
      chapterId: ch3.id,
      difficulty: 'EASY',
      questionEn: 'A square coil of side $1\\text{ m}$ and resistance $1\\,\\Omega$ is placed in a magnetic field of $0.5\\text{ T}$. If the plane of the coil is perpendicular to the direction of the magnetic field, then the magnetic flux through the coil will be:',
      questionBn: '$1\\text{ m}$ বাহু এবং $1\\,\\Omega$ রোধবিশিষ্ট একটি বর্গাকার কুণ্ডলীকে $0.5\\text{ T}$ চৌম্বক ক্ষেত্রে রাখা আছে। যদি কুণ্ডলীর তল চৌম্বক ক্ষেত্রের অভিমুখের সঙ্গে লম্ব হয়, তাহলে কুণ্ডলীর মধ্যে দিয়ে চৌম্বক প্রবাহ হবে—',
      optionA_En: '$0.5\\text{ weber}$',
      optionA_Bn: '$0.5\\text{ weber}$',
      optionB_En: '$1\\text{ weber}$',
      optionB_Bn: '$1\\text{ weber}$',
      optionC_En: '$0\\text{ weber}$',
      optionC_Bn: '$0\\text{ weber}$',
      optionD_En: '$2\\text{ weber}$',
      optionD_Bn: '$2\\text{ weber}$',
      correctOption: 'A',
      explanationEn: 'Area of the square coil $A = 1\\text{ m} \\times 1\\text{ m} = 1\\text{ m}^2$.\nWhen the plane is perpendicular to $\\vec{B}$, the area normal vector is parallel to $\\vec{B}$ ($\\theta = 0^\\circ$).\nMagnetic flux:\n$$\\Phi = B A \\cos 0^\\circ = 0.5\\text{ T} \\times 1\\text{ m}^2 \\times 1 = 0.5\\text{ Wb}$$',
      explanationBn: 'ক্ষেত্রফল $A = 1 \\times 1 = 1\\text{ m}^2$। তল চৌম্বকক্ষেত্রের সঙ্গে লম্ব হওয়ায় অভিলম্বের কোণ $\\theta = 0^\\circ$।\nচৌম্বক ফ্লাক্স:\n$$\\Phi = B A \\cos 0^\\circ = 0.5 \\times 1 = 0.5\\text{ Weber}$$',
      formula: '\\Phi = B A \\cos\\theta',
      simulationType: 'ELECTRIC_FLUX_3D',
      isPublished: true,
    },
    // --- Q11 ---
    {
      code: 'WB12-PYQ-Q011',
      chapterId: ch3.id,
      difficulty: 'EASY',
      questionEn: 'For a diamagnetic material, which of the following relations between $B$ and $H$ is correct?',
      questionBn: 'কোনো তিরশ্চৌম্বক পদার্থের ক্ষেত্রে কোনটি সঠিক?',
      optionA_En: '$B = H$',
      optionA_Bn: '$B = H$',
      optionB_En: '$B < H$',
      optionB_Bn: '$B < H$',
      optionC_En: '$B > H$',
      optionC_Bn: '$B > H$',
      optionD_En: '$B \\gg H$',
      optionD_Bn: '$B \\gg H$',
      correctOption: 'B',
      explanationEn: 'For diamagnetic materials, magnetic susceptibility is small and negative ($\\chi < 0$), so relative permeability $\\mu_r = 1 + \\chi < 1$. In Gaussian/CGS units ($B = \\mu H$), since $\\mu < 1$, we have $B < H$.',
      explanationBn: 'তিরশ্চৌম্বক পদার্থের চৌম্বক প্রবণতা ঋণাত্মক ($\\chi < 0$), ফলে আপেক্ষিক ভেদ্যতা $\\mu_r < 1$ হয়। সুতরাং $B < H$।',
      formula: 'B = \\mu H < H',
      simulationType: 'EARTH_MAGNETISM_DIPOLE',
      isPublished: true,
    },
    // --- Q12 ---
    {
      code: 'WB12-PYQ-Q012',
      chapterId: ch3.id,
      difficulty: 'MEDIUM',
      questionEn: 'The magnetic dipole moment of a straight steel wire is $M$. If it is bent into a semicircle, the new magnetic dipole moment of the wire will be:',
      questionBn: 'একটি ইস্পাতের তারের চৌম্বক ভ্রামক $M$। এটিকে বাঁকিয়ে অর্ধবৃত্তাকার করা হলে তারটির নতুন চৌম্বক ভ্রামক হবে—',
      optionA_En: '$M$',
      optionA_Bn: '$M$',
      optionB_En: '$\\dfrac{2M}{\\pi}$',
      optionB_Bn: '$\\dfrac{2M}{\\pi}$',
      optionC_En: '$\\dfrac{M}{2\\pi}$',
      optionC_Bn: '$\\dfrac{M}{2\\pi}$',
      optionD_En: '$\\dfrac{M}{\\pi}$',
      optionD_Bn: '$\\dfrac{M}{\\pi}$',
      correctOption: 'B',
      explanationEn: 'Initial dipole moment of wire of length $L$ and pole strength $m$ is $M = m L$.\nWhen bent into a semicircle of radius $r$, arc length $\\pi r = L \\implies r = \\frac{L}{\\pi}$.\nThe distance between the poles is the diameter $2r = \\frac{2L}{\\pi}$.\nNew magnetic dipole moment:\n$$M\' = m(2r) = m\\left(\\frac{2L}{\\pi}\\right) = \\frac{2(mL)}{\\pi} = \\frac{2M}{\\pi}$$',
      explanationBn: 'প্রাথমিক চৌম্বক ভ্রামক $M = m L$।\nতারটিকে অর্ধবৃত্তাকার করলে $\\pi r = L \\implies r = \\frac{L}{\\pi}$।\nমেরুদ্বয়ের মধ্যবর্তী দূরত্ব ব্যাস $= 2r = \\frac{2L}{\\pi}$।\nনতুন চৌম্বক ভ্রামক: $M\' = m(2r) = \\frac{2mL}{\\pi} = \\frac{2M}{\\pi}$।',
      formula: 'M\' = \\frac{2M}{\\pi}',
      simulationType: 'EARTH_MAGNETISM_DIPOLE',
      simulationParams: JSON.stringify({ mode: 'BENT_WIRE' }),
      isPublished: true,
    },
    // --- Q13 ---
    {
      code: 'WB12-PYQ-Q013',
      chapterId: ch3.id,
      difficulty: 'MEDIUM',
      questionEn: 'The force acting between two parallel current-carrying wires is $F$. If the current in each wire is doubled and the distance between them is tripled, the force acting between them will be:',
      questionBn: 'দুটি সমান্তরাল তড়িৎবাহী তারের মধ্যে ক্রিয়াশীল বল $F$। যদি প্রতিটি তারের প্রবাহ দ্বিগুণ ও মধ্যবর্তী দূরত্ব তিনগুণ করা হয়, তাহলে তাদের মধ্যে ক্রিয়াশীল বল হবে—',
      optionA_En: '$12 F$',
      optionA_Bn: '$12 F$',
      optionB_En: '$\\dfrac{4F}{3}$',
      optionB_Bn: '$\\dfrac{4F}{3}$',
      optionC_En: '$\\dfrac{4F}{9}$',
      optionC_Bn: '$\\dfrac{4F}{9}$',
      optionD_En: '$\\dfrac{2F}{9}$',
      optionD_Bn: '$\\dfrac{2F}{9}$',
      correctOption: 'B',
      explanationEn: 'Force per unit length between parallel wires is $F = \\frac{\\mu_0 I_1 I_2}{2\\pi d}$.\nWhen $I_1\' = 2I_1$, $I_2\' = 2I_2$, and $d\' = 3d$:\n$$F\' = \\frac{\\mu_0 (2I_1)(2I_2)}{2\\pi (3d)} = \\frac{4}{3}\\left(\\frac{\\mu_0 I_1 I_2}{2\\pi d}\\right) = \\frac{4F}{3}$$',
      explanationBn: 'সমান্তরাল তারদ্বয়ের বল $F = \\frac{\\mu_0 I_1 I_2}{2\\pi d}$।\nপ্রবাহ দ্বিগুণ ও দূরত্ব ৩ গুণ হলে: $F\' = \\frac{2 \\times 2}{3} F = \\frac{4F}{3}$।',
      formula: 'F\' = \\frac{4F}{3}',
      simulationType: 'MAGNETIC_FIELD_CURRENTS',
      simulationParams: JSON.stringify({ mode: 'PARALLEL_WIRES' }),
      isPublished: true,
    },
    // --- Q14 ---
    {
      code: 'WB12-PYQ-Q014',
      chapterId: ch3.id,
      difficulty: 'MEDIUM',
      questionEn: 'The ratio of the radii of two circular coils is $1:2$. If the ratio of their magnetic dipole moments is $1:2$, the ratio of the electric currents flowing through them will be:',
      questionBn: 'দুটি বৃত্তাকার কুণ্ডলীর ব্যাসার্ধের অনুপাত $1:2$। এদের চৌম্বক ভ্রামকের অনুপাত $1:2$ হলে, এদের মধ্যে দিয়ে প্রবাহিত তড়িৎপ্রবাহের অনুপাত হবে—',
      optionA_En: '$1:1$',
      optionA_Bn: '$1:1$',
      optionB_En: '$2:1$',
      optionB_Bn: '$2:1$',
      optionC_En: '$4:1$',
      optionC_Bn: '$4:1$',
      optionD_En: '$1:4$',
      optionD_Bn: '$1:4$',
      correctOption: 'B',
      explanationEn: 'Magnetic dipole moment of a circular coil is $M = I A = I (\\pi r^2)$.\n$$\\frac{M_1}{M_2} = \\frac{I_1 r_1^2}{I_2 r_2^2} \\implies \\frac{1}{2} = \\frac{I_1}{I_2} \\left(\\frac{1}{2}\\right)^2 = \\frac{I_1}{I_2} \\times \\frac{1}{4}$$\n$$\\implies \\frac{I_1}{I_2} = \\frac{1/2}{1/4} = \\frac{4}{2} = 2:1$$',
      explanationBn: 'চৌম্বক ভ্রামক $M = I \\pi r^2$।\n$$\\frac{M_1}{M_2} = \\frac{I_1}{I_2}\\left(\\frac{r_1}{r_2}\\right)^2 \\implies \\frac{1}{2} = \\frac{I_1}{I_2} \\times \\frac{1}{4} \\implies \\frac{I_1}{I_2} = 2:1$$',
      formula: 'M = I \\pi r^2',
      simulationType: 'MAGNETIC_FIELD_CURRENTS',
      simulationParams: JSON.stringify({ mode: 'CIRCULAR_LOOP' }),
      isPublished: true,
    },
    // --- Q15 ---
    {
      code: 'WB12-PYQ-Q015',
      chapterId: ch2.id,
      difficulty: 'EASY',
      questionEn: 'In which case will the null condition (balanced state) of a Wheatstone bridge change?',
      questionBn: 'কোন্ ক্ষেত্রে হুইটস্টোন ব্রিজের নিষ্পন্দ অবস্থাটি পরিবর্তিত হবে?',
      optionA_En: 'If the resistances of the different arms are changed',
      optionA_Bn: 'বিভিন্ন বাহুর রোধগুলিকে পরিবর্তিত করা হলে',
      optionB_En: 'If positions of battery and galvanometer are interchanged',
      optionB_Bn: 'ব্যাটারির ও গ্যালাভানোমিটারের অবস্থান বিনিময় করা হলে',
      optionC_En: 'If a battery of different EMF is used',
      optionC_Bn: 'অন্য তড়িৎচালক বলের ব্যাটারি নিলে',
      optionD_En: 'If a galvanometer of different resistance is used',
      optionD_Bn: 'অন্য রোধের গ্যালাভানোমিটার নিলে',
      correctOption: 'A',
      explanationEn: 'The Wheatstone bridge balance condition is $\\frac{P}{Q} = \\frac{R}{S}$. Interchanging the battery and galvanometer, or changing battery EMF, or changing galvanometer resistance does NOT affect the null point condition. Only changing the resistance values in the arms will alter the balance condition.',
      explanationBn: 'হুইটস্টোন ব্রিজের সাম্যাবস্থার শর্ত $\\frac{P}{Q} = \\frac{R}{S}$। ব্যাটারি ও গ্যালভানোমিটারের স্থান বিনিময় বা এদের মান পরিবর্তন করলে সাম্যাবস্থা পরিবর্তিত হয় না। কেবল বাহুর রোধ পরিবর্তন করলেই নিষ্পন্দ অবস্থা পরিবর্তিত হয়।',
      formula: '\\frac{P}{Q} = \\frac{R}{S}',
      simulationType: 'CIRCUIT_INSTRUMENTS',
      simulationParams: JSON.stringify({ mode: 'WHEATSTONE' }),
      isPublished: true,
    },
    // --- Q16 ---
    {
      code: 'WB12-PYQ-Q016',
      chapterId: ch1.id,
      difficulty: 'EASY',
      questionEn: 'The electric field lines in a region are shown in the figure. At which point is the electric field intensity the greatest?',
      questionBn: 'নীচের চিত্রে একটি তড়িৎক্ষেত্রের বলরেখা দেখানো হয়েছে। কোন্ বিন্দুতে তড়িৎ ক্ষেত্রপ্রাবলের মান সবথেকে বেশি?',
      optionA_En: 'A',
      optionA_Bn: 'A',
      optionB_En: 'B',
      optionB_Bn: 'B',
      optionC_En: 'C',
      optionC_Bn: 'C',
      optionD_En: 'D',
      optionD_Bn: 'D',
      correctOption: 'A',
      explanationEn: 'The density or crowding of electric field lines represents the magnitude of the electric field intensity ($E$). In the given diagram, the field lines are most densely packed near point A. Therefore, electric field intensity is maximum at point A.',
      explanationBn: 'তড়িৎ বলরেখার ঘনত্ব তড়িৎক্ষেত্র প্রাবল্যের মান নির্দেশ করে। চিত্রে A বিন্দুর কাছে বলরেখাগুলি সবচেয়ে ঘন সন্নিবিষ্ট। তাই A বিন্দুতে ক্ষেত্রপ্রাবল্য সর্বাধিক।',
      formula: 'E \\propto \\text{Line Density}',
      simulationType: 'EARTH_MAGNETISM_DIPOLE',
      simulationParams: JSON.stringify({ mode: 'FIELD_LINES' }),
      isPublished: true,
    },
    // --- Q17 ---
    {
      code: 'WB12-PYQ-Q017',
      chapterId: ch1.id,
      difficulty: 'MEDIUM',
      questionEn: 'Two point charges in air are separated by a distance of $0.18\\text{ m}$. One charge is $4$ times the other. If the electric field is zero at a point on the line joining the two charges, the position of that point is:',
      questionBn: 'বায়ু মাধ্যমে থাকা দুটি বিন্দু-আধান পরস্পরের থেকে $0.18\\text{ m}$ দূরে আছে। একটি আধানের মান অপরটির $4$ গুণ। আধান দুটির সংযোগকারী রেখার ওপর একটি বিন্দুতে তড়িৎক্ষেত্রের মান শূন্য হলে, বিন্দুটির অবস্থান হবে—',
      optionA_En: 'Outside the two charges on the line and $0.06\\text{ m}$ from the larger charge',
      optionA_Bn: 'রেখার ওপর আধান দুটির বাইরে এবং বৃহত্তর আধান থেকে $0.06\\text{ m}$ দূরে',
      optionB_En: 'Between the two charges on the line and $0.06\\text{ m}$ from the smaller charge',
      optionB_Bn: 'রেখার ওপর আধান দুটির মধ্যবর্তী স্থানে এবং ক্ষুদ্রতর আধান থেকে $0.06\\text{ m}$ দূরে',
      optionC_En: 'Between the two charges on the line and $0.04\\text{ m}$ from the larger charge',
      optionC_Bn: 'রেখার ওপর আধান দুটির মধ্যবর্তী স্থানে এবং বৃহত্তর আধান থেকে $0.04\\text{ m}$ দূরে',
      optionD_En: 'Outside the two charges on the line and $0.04\\text{ m}$ from the smaller charge',
      optionD_Bn: 'রেখার ওপর আধান দুটির বাইরে এবং ক্ষুদ্রতর আধান থেকে $0.04\\text{ m}$ দূরে',
      correctOption: 'B',
      explanationEn: 'For two like charges $q$ and $4q$ separated by $d = 0.18\\text{ m}$, the null point lies between them at distance $x$ from $q$:\n$$\\frac{k q}{x^2} = \\frac{k (4q)}{(d - x)^2} \\implies \\frac{1}{x} = \\frac{2}{d - x} \\implies d - x = 2x \\implies 3x = d = 0.18\\text{ m} \\implies x = 0.06\\text{ m}$$\nThus, the null point is between the two charges at $0.06\\text{ m}$ from the smaller charge.',
      explanationBn: 'দুটি সমজাতীয় আধান $q$ ও $4q$-এর মাঝে $x$ দূরত্বে তড়িৎক্ষেত্র শূন্য হলে:\n$$\\frac{k q}{x^2} = \\frac{k (4q)}{(0.18 - x)^2} \\implies \\frac{1}{x} = \\frac{2}{0.18 - x} \\implies 3x = 0.18 \\implies x = 0.06\\text{ m}$$',
      formula: '\\frac{q_1}{x^2} = \\frac{q_2}{(d-x)^2}',
      simulationType: 'EARTH_MAGNETISM_DIPOLE',
      simulationParams: JSON.stringify({ mode: 'NULL_POINT' }),
      isPublished: true,
    },
    // --- Q18 ---
    {
      code: 'WB12-PYQ-Q018',
      chapterId: ch1.id,
      difficulty: 'MEDIUM',
      questionEn: 'The electric field intensity at an axial point at a distance $r$ from the center of an electric dipole is $E$. The dipole is rotated by $90^\\circ$ about a perpendicular axis. Now the electric field intensity at that same point will be:',
      questionBn: 'একটি তড়িৎ দ্বিমেরুর কেন্দ্র থেকে $r$ দূরত্বে অক্ষীয় অবস্থানে কোনো বিন্দুতে তড়িৎ ক্ষেত্রপ্রাবল্য $E$। দ্বিমেরুটিকে উল্লম্ব অক্ষের সাপেক্ষে $90^\\circ$ কোণে ঘোরানো হল। এখন ওই আগের বিন্দুতে তড়িৎ ক্ষেত্রপ্রাবল্য হবে—',
      optionA_En: '$E$',
      optionA_Bn: '$E$',
      optionB_En: '$\\dfrac{E}{4}$',
      optionB_Bn: '$\\dfrac{E}{4}$',
      optionC_En: '$\\dfrac{E}{2}$',
      optionC_Bn: '$\\dfrac{E}{2}$',
      optionD_En: '$2E$',
      optionD_Bn: '$2E$',
      correctOption: 'C',
      explanationEn: 'Initially, the point is in the axial position: $E_{\\text{axial}} = \\frac{2kp}{r^3} = E$.\nWhen the dipole is rotated by $90^\\circ$, that point now lies on the equatorial (broadside-on) axis:\n$$E_{\\text{equatorial}} = \\frac{kp}{r^3} = \\frac{E_{\\text{axial}}}{2} = \\frac{E}{2}$$',
      explanationBn: 'অক্ষীয় অবস্থানে $E_{\\text{axial}} = \\frac{2kp}{r^3} = E$।\nদ্বিমেরুকে $90^\\circ$ ঘোরালে বিন্দুটি নিরক্ষীয় অবস্থানে পরিণত হয়:\n$$E_{\\text{equatorial}} = \\frac{kp}{r^3} = \\frac{E}{2}$$',
      formula: 'E_{\\text{eq}} = \\frac{E_{\\text{ax}}}{2}',
      simulationType: 'EARTH_MAGNETISM_DIPOLE',
      simulationParams: JSON.stringify({ mode: 'ROTATED_DIPOLE' }),
      isPublished: true,
    },
    // --- Q19 ---
    {
      code: 'WB12-PYQ-Q019',
      chapterId: ch1.id,
      difficulty: 'EASY',
      questionEn: 'Let the surface charge density of an infinite thin plane sheet of positive charge be $\\sigma$. The electric field intensity at a nearby point P at distance $r$ is $E$. How does the electric field vary with distance $r$?',
      questionBn: 'ধরা যাক, ধনাত্মক আধানে আহিত একটি অসীম পাতলা সমতল পাতের তলমাত্রিক আধান ঘনত্ব হল $\\sigma$। পাতটির কাছাকাছি $r$ দূরত্বে P বিন্দুতে তড়িৎক্ষেত্রের প্রাবলের মান হল $E$। দূরত্বের সঙ্গে তড়িৎক্ষেত্রের মান কীভাবে পরিবর্তিত হবে?',
      optionA_En: '$E \\propto 1/r^2$ (Curve)',
      optionA_Bn: '$E \\propto 1/r^2$ (বক্ররেখা)',
      optionB_En: 'Linear piecewise graph',
      optionB_Bn: 'রৈখিক বৃদ্ধি',
      optionC_En: 'Directly proportional line',
      optionC_Bn: 'মূলবিন্দুগামী সরলরেখা',
      optionD_En: 'Horizontal straight line (constant with $r$)',
      optionD_Bn: 'দূরত্ব নিরপেক্ষ আনুভূমিক সরলরেখা',
      correctOption: 'D',
      explanationEn: 'The electric field near an infinite thin charged plane sheet is $E = \\frac{\\sigma}{2\\varepsilon_0}$. This field is uniform and completely independent of the distance $r$. Hence the graph of $E$ vs $r$ is a horizontal straight line parallel to the $r$-axis.',
      explanationBn: 'অসীম সমতল পাতের নিকটবর্তী বিন্দুতে তড়িৎক্ষেত্র $E = \\frac{\\sigma}{2\\varepsilon_0}$। এটি দূরত্বের উপর নির্ভর করে না (ধ্রুবক), তাই $E-r$ লেখচিত্র একটি অনুভূমিক সরলরেখা।',
      formula: 'E = \\frac{\\sigma}{2\\varepsilon_0}',
      simulationType: 'ELECTRIC_FLUX_3D',
      isPublished: true,
    },
    // --- Q20 ---
    {
      code: 'WB12-PYQ-Q020',
      chapterId: ch1.id,
      difficulty: 'MEDIUM',
      questionEn: 'Three capacitors of capacitances $1.0\\,\\mu\\text{F}$, $2.0\\,\\mu\\text{F}$ and $5.0\\,\\mu\\text{F}$ are connected in series across a $10\\text{ V}$ source. The potential difference across the $2.0\\,\\mu\\text{F}$ capacitor will be:',
      questionBn: '$1.0\\,\\mu\\text{F}$, $2.0\\,\\mu\\text{F}$ এবং $5.0\\,\\mu\\text{F}$ ধারকত্বের তিনটি ধারক একটি $10\\text{ V}$ উৎসের সঙ্গে শ্রেণি সমবায়ে যুক্ত। $2.0\\,\\mu\\text{F}$ ধারকত্বের ধারকটির দুই প্রান্তের বিভবপার্থক্য হবে—',
      optionA_En: '$\\dfrac{100}{17}\\text{ V}$',
      optionA_Bn: '$\\dfrac{100}{17}\\text{ V}$',
      optionB_En: '$\\dfrac{20}{17}\\text{ V}$',
      optionB_Bn: '$\\dfrac{20}{17}\\text{ V}$',
      optionC_En: '$\\dfrac{50}{17}\\text{ V}$',
      optionC_Bn: '$\\dfrac{50}{17}\\text{ V}$',
      optionD_En: '$10\\text{ V}$',
      optionD_Bn: '$10\\text{ V}$',
      correctOption: 'C',
      explanationEn: 'Equivalent capacitance in series:\n$$\\frac{1}{C_{\\text{eq}}} = \\frac{1}{1} + \\frac{1}{2} + \\frac{1}{5} = \\frac{10 + 5 + 2}{10} = \\frac{17}{10}\\,\\mu\\text{F}^{-1} \\implies C_{\\text{eq}} = \\frac{10}{17}\\,\\mu\\text{F}$$\nTotal charge stored:\n$$Q = C_{\\text{eq}} V = \\left(\\frac{10}{17}\\right) \\times 10 = \\frac{100}{17}\\,\\mu\\text{C}$$\nPotential difference across the $2.0\\,\\mu\\text{F}$ capacitor:\n$$V_2 = \\frac{Q}{C_2} = \\frac{100/17}{2} = \\frac{50}{17}\\text{ V}$$',
      explanationBn: 'শ্রেণি সমবায়ে তুল্য ধারকত্ব:\n$$\\frac{1}{C_{\\text{eq}}} = \\frac{1}{1} + \\frac{1}{2} + \\frac{1}{5} = \\frac{17}{10} \\implies C_{\\text{eq}} = \\frac{10}{17}\\,\\mu\\text{F}$$\nমোট আধান $Q = C_{\\text{eq}} \\times 10 = \\frac{100}{17}\\,\\mu\\text{C}$।\n$2.0\\,\\mu\\text{F}$-এর বিভবপার্থক্য: $V_2 = \\frac{Q}{2} = \\frac{50}{17}\\text{ V}$।',
      formula: 'V_2 = \\frac{Q}{C_2} = \\frac{C_{\\text{eq}} V}{C_2}',
      simulationType: 'CAPACITOR_DIELECTRIC',
      isPublished: true,
    },
    // --- Q21 ---
    {
      code: 'WB12-PYQ-Q021',
      chapterId: ch4.id,
      difficulty: 'EASY',
      questionEn: 'The dimensional formula of mutual inductance ($M$) is:',
      questionBn: 'পারস্পরিক আবেশ গুণাঙ্কের মাত্রীয় সংকেত হল—',
      optionA_En: '$\\text{ML}^2\\text{T}^{-2}\\text{I}^2$',
      optionA_Bn: '$\\text{ML}^2\\text{T}^{-2}\\text{I}^2$',
      optionB_En: '$\\text{ML}^2\\text{T}^{-2}\\text{I}^{-2}$',
      optionB_Bn: '$\\text{ML}^2\\text{T}^{-2}\\text{I}^{-2}$',
      optionC_En: '$\\text{ML}^{-2}\\text{T}^2\\text{I}^2$',
      optionC_Bn: '$\\text{ML}^{-2}\\text{T}^2\\text{I}^2$',
      optionD_En: '$\\text{ML}^{-2}\\text{T}^{-2}\\text{I}^{-2}$',
      optionD_Bn: '$\\text{ML}^{-2}\\text{T}^{-2}\\text{I}^{-2}$',
      correctOption: 'B',
      explanationEn: 'Magnetic energy in an inductor is $U = \\frac{1}{2} M I^2 \\implies M = \\frac{2U}{I^2}$.\nDimensions of energy $U = [\\text{M}\\text{L}^2\\text{T}^{-2}]$.\nDimensions of current $I = [\\text{I}]$.\n$$[M] = \\frac{[\\text{M}\\text{L}^2\\text{T}^{-2}]}{[\\text{I}^2]} = [\\text{ML}^2\\text{T}^{-2}\\text{I}^{-2}]$$',
      explanationBn: 'চৌম্বক শক্তি $U = \\frac{1}{2} M I^2 \\implies M = \\frac{2U}{I^2}$।\nশক্তির মাত্রা $[U] = [\\text{M}\\text{L}^2\\text{T}^{-2}]$।\nআবেশাঙ্কের মাত্রা $[M] = [\\text{ML}^2\\text{T}^{-2}\\text{I}^{-2}]$।',
      formula: '[M] = [\\text{ML}^2\\text{T}^{-2}\\text{I}^{-2}]',
      simulationType: 'AC_CIRCUITS_TRANSFORMER',
      isPublished: true,
    },
    // --- Q22 ---
    {
      code: 'WB12-PYQ-Q022',
      chapterId: ch4.id,
      difficulty: 'MEDIUM',
      questionEn: 'Statement I: Direct current (dc) is less dangerous than alternating current (ac).\nStatement II: The rms value of alternating current (ac) is 70.7% of its peak value.\nWhich option is correct?',
      questionBn: 'বিবৃতি I: পরিবর্তী প্রবাহের (ac) তুলনায় সমপ্রবাহ (dc) কম বিপজ্জনক।\nবিবৃতি II: পরিবর্তী প্রবাহমাত্রার (ac) rms মান শীর্ষমানের 70.7%।\nকোন বিকল্পটি সঠিক?',
      optionA_En: 'Only Statement I is true',
      optionA_Bn: 'শুধুমাত্র বিবৃতি I সত্য',
      optionB_En: 'Only Statement II is true',
      optionB_Bn: 'শুধুমাত্র বিবৃতি II সত্য',
      optionC_En: 'Both Statement I and II are true',
      optionC_Bn: 'বিবৃতি I ও II উভয়ই সত্য',
      optionD_En: 'Both Statement I and II are false',
      optionD_Bn: 'বিবৃতি I ও II উভয়ই মিথ্যা',
      correctOption: 'C',
      explanationEn: '- Statement I is TRUE: AC is more dangerous than DC because AC peak voltage is $\\sqrt{2} \\times V_{\\text{rms}} \\approx 1.414 V$, and AC induces severe muscle contraction (tetany) and cardiac fibrillation.\n- Statement II is TRUE: $I_{\\text{rms}} = \\frac{I_0}{\\sqrt{2}} \\approx 0.7071 I_0 = 70.7\\%$ of peak value.\nTherefore, both Statements I and II are true.',
      explanationBn: '- বিবৃতি I সত্য: সমবিভব ac-এর শীর্ষমান dc অপেক্ষা বেশি ($\\sqrt{2}$ গুণ) হওয়ায় ac বেশি বিপজ্জনক, অর্থাৎ dc কম বিপজ্জনক।\n- বিবৃতি II সত্য: $I_{\\text{rms}} = \\frac{I_0}{\\sqrt{2}} = 0.707 I_0 = 70.7\\%$।\nঅতএব উভয় বিবৃতিই সত্য।',
      formula: 'I_{\\text{rms}} = \\frac{I_0}{\\sqrt{2}} = 0.707 I_0',
      simulationType: 'AC_CIRCUITS_TRANSFORMER',
      simulationParams: JSON.stringify({ mode: 'AC_SINE_RMS' }),
      isPublished: true,
    },
    // --- Q23 ---
    {
      code: 'WB12-PYQ-Q023',
      chapterId: ch5.id,
      difficulty: 'MEDIUM',
      questionEn: 'An electromagnetic wave is propagating along the $+X$-axis in vacuum. If at a particular location and time, the magnetic field is $\\vec{B} = 2.4 \\times 10^{-8}\\hat{k}\\text{ tesla}$, then at that point $\\vec{E}$ in V/m will be:',
      questionBn: 'শূন্য মাধ্যমে একটি তড়িৎচুম্বকীয় তরঙ্গ $X$-অক্ষ বরাবর গতিশীল। যদি কোনো একটি নির্দিষ্ট অবস্থানে এবং সময়ে $\\vec{B}$-এর মান $2.4 \\times 10^{-8}\\hat{k}\\text{ tesla}$ হয়, তাহলে ওই বিন্দুতে $\\vec{E}$, V/m এককে হবে—',
      optionA_En: '$7.2\\,\\hat{j}$',
      optionA_Bn: '$7.2\\,\\hat{j}$',
      optionB_En: '$7.2\\,\\hat{i}$',
      optionB_Bn: '$7.2\\,\\hat{i}$',
      optionC_En: '$0.8\\,\\hat{k}$',
      optionC_Bn: '$0.8\\,\\hat{k}$',
      optionD_En: '$2.4\\,\\hat{k}$',
      optionD_Bn: '$2.4\\,\\hat{k}$',
      correctOption: 'A',
      explanationEn: 'Magnitude: $E = c B = (3 \\times 10^8\\text{ m/s}) \\times (2.4 \\times 10^{-8}\\text{ T}) = 7.2\\text{ V/m}$.\nDirection: Propagation vector is $\\hat{k}_{\\text{wave}} = \\hat{i}$.\nPoynting vector requires $\\hat{E} \\times \\hat{B} = \\hat{i}$.\nSince $\\hat{B} = \\hat{k}$, we know $\\hat{j} \\times \\hat{k} = \\hat{i}$.\nTherefore, $\\vec{E} = 7.2\\hat{j}\\text{ V/m}$.',
      explanationBn: 'মান: $E = c B = (3 \\times 10^8)(2.4 \\times 10^{-8}) = 7.2\\text{ V/m}$।\nঅভিমুখ: তরঙ্গ $+X$ অক্ষ ($\\hat{i}$) বরাবর চলছে।\n$\\hat{E} \\times \\hat{B} = \\hat{i} \\implies \\hat{j} \\times \\hat{k} = \\hat{i}$।\nঅতএব $\\vec{E} = 7.2\\hat{j}\\text{ V/m}$।',
      formula: 'E = c B, \\quad \\hat{E} \\times \\hat{B} = \\hat{S}',
      simulationType: 'EM_WAVES_SPECTRUM',
      simulationParams: JSON.stringify({ mode: '3D_WAVE' }),
      isPublished: true,
    },
    // --- Q24 ---
    {
      code: 'WB12-PYQ-Q024',
      chapterId: ch5.id,
      difficulty: 'EASY',
      questionEn: 'Match Column-I with Column-II:\nColumn-I: (i) Infrared, (ii) Micro wave, (iii) X-ray, (iv) Radio wave\nColumn-II: (a) $10^{-2}\\text{ m}$, (b) $10^3\\text{ m}$, (c) $10^{-7}\\text{ m}$, (d) $10^{-9}\\text{ m}$',
      questionBn: 'স্তম্ভ-I এর সাথে স্তম্ভ-II মেলাও এবং সঠিক উত্তরটি বেছে নাও:\nস্তম্ভ-১: (i) অবলোহিত তরঙ্গ, (ii) মাইক্রো তরঙ্গ, (iii) X-রশ্মি, (iv) রেডিও তরঙ্গ\nস্তম্ভ-২: (a) $10^{-2}\\text{ m}$, (b) $10^3\\text{ m}$, (c) $10^{-7}\\text{ m}$, (d) $10^{-9}\\text{ m}$',
      optionA_En: '(i)-(d), (ii)-(a), (iii)-(b), (iv)-(c)',
      optionA_Bn: '(i)-(d), (ii)-(a), (iii)-(b), (iv)-(c)',
      optionB_En: '(i)-(d), (ii)-(c), (iii)-(b), (iv)-(a)',
      optionB_Bn: '(i)-(d), (ii)-(c), (iii)-(b), (iv)-(a)',
      optionC_En: '(i)-(c), (ii)-(d), (iii)-(a), (iv)-(b)',
      optionC_Bn: '(i)-(c), (ii)-(d), (iii)-(a), (iv)-(b)',
      optionD_En: '(i)-(c), (ii)-(a), (iii)-(d), (iv)-(b)',
      optionD_Bn: '(i)-(c), (ii)-(a), (iii)-(d), (iv)-(b)',
      correctOption: 'D',
      explanationEn: 'Matching wavelengths:\n- Radio wave: $\\lambda \\sim 10^3\\text{ m}$ ⟹ (iv)-(b)\n- Micro wave: $\\lambda \\sim 10^{-2}\\text{ m}$ ⟹ (ii)-(a)\n- Infrared: $\\lambda \\sim 10^{-7}\\text{ m}$ ⟹ (i)-(c)\n- X-ray: $\\lambda \\sim 10^{-9}\\text{ m}$ ⟹ (iii)-(d)\nHence Option (D) is correct.',
      explanationBn: 'তরঙ্গদৈর্ঘ্য মিলিয়ে:\n- রেডিও তরঙ্গ: $10^3\\text{ m}$ ⟹ (iv)-(b)\n- মাইক্রো তরঙ্গ: $10^{-2}\\text{ m}$ ⟹ (ii)-(a)\n- অবলোহিত তরঙ্গ: $10^{-7}\\text{ m}$ ⟹ (i)-(c)\n- X-রশ্মি: $10^{-9}\\text{ m}$ ⟹ (iii)-(d)\nসঠিক ক্রম: (i)-(c), (ii)-(a), (iii)-(d), (iv)-(b)।',
      formula: '\\lambda_{\\text{radio}} > \\lambda_{\\text{micro}} > \\lambda_{\\text{IR}} > \\lambda_{\\text{X-ray}}',
      simulationType: 'EM_WAVES_SPECTRUM',
      isPublished: true,
    },
    // --- Q25 ---
    {
      code: 'WB12-PYQ-Q025',
      chapterId: ch5.id,
      difficulty: 'MEDIUM',
      questionEn: 'The velocity of electromagnetic radiation in a medium having permittivity $\\frac{\\varepsilon_0}{2}$ and permeability $2\\mu_0$ is:',
      questionBn: 'তড়িৎভেদ্যতা $\\frac{\\varepsilon_0}{2}$ এবং চৌম্বক ভেদ্যতা $2\\mu_0$ বিশিষ্ট একটি মাধ্যমে তড়িৎচুম্বকীয় বিকিরণ-এর বেগ হল—',
      optionA_En: '$2\\sqrt{\\dfrac{\\varepsilon_0}{\\mu_0}}$',
      optionA_Bn: '$2\\sqrt{\\dfrac{\\varepsilon_0}{\\mu_0}}$',
      optionB_En: '$2\\sqrt{\\mu_0\\varepsilon_0}$',
      optionB_Bn: '$2\\sqrt{\\mu_0\\varepsilon_0}$',
      optionC_En: '$\\dfrac{1}{\\sqrt{\\mu_0\\varepsilon_0}}$',
      optionC_Bn: '$\\dfrac{1}{\\sqrt{\\mu_0\\varepsilon_0}}$',
      optionD_En: '$\\dfrac{1}{2}\\sqrt{\\dfrac{\\mu_0}{\\varepsilon_0}}$',
      optionD_Bn: '$\\dfrac{1}{2}\\sqrt{\\dfrac{\\mu_0}{\\varepsilon_0}}$',
      correctOption: 'C',
      explanationEn: 'The speed of an electromagnetic wave in any medium is given by $v = \\frac{1}{\\sqrt{\\mu \\varepsilon}}$.\nGiven $\\mu = 2\\mu_0$ and $\\varepsilon = \\frac{\\varepsilon_0}{2}$:\n$$v = \\frac{1}{\\sqrt{(2\\mu_0)\\left(\\frac{\\varepsilon_0}{2}\\right)}} = \\frac{1}{\\sqrt{\\mu_0 \\varepsilon_0}} = c$$',
      explanationBn: 'মাধ্যমে আলোর বেগ $v = \\frac{1}{\\sqrt{\\mu \\varepsilon}}$।\n$$v = \\frac{1}{\\sqrt{2\\mu_0 \\times \\frac{\\varepsilon_0}{2}}} = \\frac{1}{\\sqrt{\\mu_0 \\varepsilon_0}} = c$$',
      formula: 'v = \\frac{1}{\\sqrt{\\mu\\varepsilon}} = \\frac{1}{\\sqrt{\\mu_0\\varepsilon_0}}',
      simulationType: 'EM_WAVES_SPECTRUM',
      isPublished: true,
    },
    // --- Q26 ---
    {
      code: 'WB12-PYQ-Q026',
      chapterId: ch2.id,
      difficulty: 'HARD',
      questionEn: 'The equivalent resistance between points A and B in the circuit network shown in the figure will be:',
      questionBn: 'নীচে দেওয়া বর্তনীতে A এবং B বিন্দু দুটির মধ্যে তুল্য রোধ হবে—',
      optionA_En: '$4\\,\\Omega$',
      optionA_Bn: '$4\\,\\Omega$',
      optionB_En: '$1\\,\\Omega$',
      optionB_Bn: '$1\\,\\Omega$',
      optionC_En: '$3\\,\\Omega$',
      optionC_Bn: '$3\\,\\Omega$',
      optionD_En: '$2\\,\\Omega$',
      optionD_Bn: '$2\\,\\Omega$',
      correctOption: 'B',
      explanationEn: 'By applying delta-star transformation / bridge simplification on the ladder network, the total equivalent resistance between terminals A and B evaluates to $R_{AB} = 1\\,\\Omega$.',
      explanationBn: 'বর্তনীটির শাখাগুলির শ্রেণি ও সমান্তরাল সমবায় বিশ্লেষণ করলে A ও B বিন্দুর মধ্যবর্তী তুল্য রোধ পাওয়া যায় $R_{AB} = 1\\,\\Omega$।',
      formula: 'R_{AB} = 1\\,\\Omega',
      simulationType: 'CIRCUIT_INSTRUMENTS',
      isPublished: true,
    },
    // --- Q27 ---
    {
      code: 'WB12-PYQ-Q027',
      chapterId: ch2.id,
      difficulty: 'HARD',
      questionEn: 'A potentiometer wire has length $100\\text{ cm}$ and resistance $10\\,\\Omega$. It is connected in series with a resistance $R$ and a $2\\text{ V}$ accumulator of negligible internal resistance. A source of EMF $10\\text{ mV}$ is balanced against a length of $40\\text{ cm}$ of the potentiometer wire. What is the value of $R$ in ohms?',
      questionBn: 'একটি পোটেনশিওমিটার তারের দৈর্ঘ্য $100\\text{ cm}$ এবং রোধ $10\\,\\Omega$। এটি $R$ এবং $2\\text{ V}$ তড়িৎচালক বল এবং নগণ্য অভ্যন্তরীণ রোধবিশিষ্ট একটি সঞ্চায়ক কোষের সঙ্গে শ্রেণিতে যুক্ত আছে। $10\\text{ mV}$ তড়িৎচালক বলের একটি উৎস পোটেনশিওমিটার তারের $40\\text{ cm}$ দৈর্ঘ্যের সঙ্গে প্রতিমিত হয়। ওহম এককে $R$-এর মান কত?',
      optionA_En: '$700$',
      optionA_Bn: '$700$',
      optionB_En: '$750$',
      optionB_Bn: '$750$',
      optionC_En: '$790$',
      optionC_Bn: '$790$',
      optionD_En: '$800$',
      optionD_Bn: '$800$',
      correctOption: 'C',
      explanationEn: 'Current in primary wire: $I = \\frac{2}{R + 10}$.\nPotential gradient across $100\\text{ cm}$ wire ($R_w = 10\\,\\Omega$):\n$$k = \\frac{I R_w}{L} = \\frac{\\frac{2}{R+10} \\times 10}{100} = \\frac{0.2}{R + 10}\\text{ V/cm}$$\nBalancing $E\' = 10\\text{ mV} = 0.01\\text{ V}$ across $l = 40\\text{ cm}$:\n$$E\' = k \\cdot l \\implies 0.01 = \\left(\\frac{0.2}{R + 10}\\right) \\times 40 = \\frac{8}{R + 10}$$\n$$R + 10 = \\frac{8}{0.01} = 800 \\implies R = 790\\,\\Omega$$',
      explanationBn: 'প্রাথমিক প্রবাহ $I = \\frac{2}{R+10}$।\nবিভব নতিমাত্রা $k = \\frac{I \\times 10}{100} = \\frac{0.2}{R+10}\\text{ V/cm}$।\n$10\\text{ mV} = 0.01\\text{ V}$ বিভব $40\\text{ cm}$-এ প্রতিমিত হলে:\n$$0.01 = \\frac{0.2 \\times 40}{R+10} = \\frac{8}{R+10} \\implies R+10 = 800 \\implies R = 790\\,\\Omega$$',
      formula: 'R = \\frac{V_0 R_w l}{E\' L} - R_w = 790\\,\\Omega',
      simulationType: 'CIRCUIT_INSTRUMENTS',
      simulationParams: JSON.stringify({ mode: 'POTENTIOMETER', balanceLength: 40 }),
      isPublished: true,
    },
    // --- Q28 ---
    {
      code: 'WB12-PYQ-Q028',
      chapterId: ch2.id,
      difficulty: 'MEDIUM',
      questionEn: '18 identical cells are grouped in a mixed combination to deliver maximum current through an external resistor. If 6 cells are in series in each row and there are 3 parallel rows, the ratio of the external resistance to the internal resistance of one cell ($R : r$) is:',
      questionBn: '18টি সদৃশ তড়িৎকোষকে মিশ্র সমবায়ে এরূপভাবে সাজানো হল যাতে একটি বহিঃস্থ রোধের মধ্য দিয়ে সর্বোচ্চ প্রবাহ যায়। যদি 6টি কোষ শ্রেণি সমবায়ে এবং এরূপ সমান্তরাল সারি যুক্ত থাকে, তাহলে বহিঃস্থ রোধ এবং একটি কোষের অভ্যন্তরীণ রোধের অনুপাত হল—',
      optionA_En: '$10:1$',
      optionA_Bn: '$10:1$',
      optionB_En: '$5:1$',
      optionB_Bn: '$5:1$',
      optionC_En: '$4:1$',
      optionC_Bn: '$4:1$',
      optionD_En: '$2:1$',
      optionD_Bn: '$2:1$',
      correctOption: 'D',
      explanationEn: 'For maximum current in mixed grouping, external resistance must equal total internal resistance:\n$$R = \\frac{n r}{m}$$\nHere $n = 6$ cells per series row. Total cells $N = m \\times n = 18 \\implies m = 3$ rows.\n$$\\frac{R}{r} = \\frac{n}{m} = \\frac{6}{3} = \\frac{2}{1} = 2:1$$',
      explanationBn: 'মিশ্র সমবায়ে সর্বোচ্চ প্রবাহের শর্ত: $R = \\frac{n r}{m}$।\nপ্রতি সারিতে $n = 6$, মোট সারি $m = 18/6 = 3$।\nঅতএব অনুপাত $\\frac{R}{r} = \\frac{6}{3} = 2:1$।',
      formula: '\\frac{R}{r} = \\frac{n}{m} = 2:1',
      simulationType: 'CIRCUIT_INSTRUMENTS',
      isPublished: true,
    },
    // --- Q29 ---
    {
      code: 'WB12-PYQ-Q029',
      chapterId: ch2.id,
      difficulty: 'EASY',
      questionEn: 'The $I\\text{-}V$ characteristics of a metallic wire at three different temperatures ($T_1$, $T_2$, and $T_3$) are shown in the figure. In this case, it can be concluded that:',
      questionBn: 'চিত্রে তিনটি ভিন্ন উষ্ণতায় ($T_1$, $T_2$ এবং $T_3$) একটি ধাতব তারের I-V লেখচিত্র দেখানো হয়েছে। এক্ষেত্রে এই সিদ্ধান্তে আসা যায় যে—',
      optionA_En: '$T_1 > T_2 > T_3$',
      optionA_Bn: '$T_1 > T_2 > T_3$',
      optionB_En: '$T_1 < T_2 < T_3$',
      optionB_Bn: '$T_1 < T_2 < T_3$',
      optionC_En: '$T_1 = T_2 = T_3$',
      optionC_Bn: '$T_1 = T_2 = T_3$',
      optionD_En: '$T_1 = T_2 > T_3$',
      optionD_Bn: '$T_1 = T_2 > T_3$',
      correctOption: 'B',
      explanationEn: 'In an $I\\text{-}V$ graph (with $I$ on the vertical axis), the slope represents conductance $\\frac{I}{V} = \\frac{1}{R}$.\n- Highest slope ($T_1$) $\\implies$ lowest resistance $R_1$.\n- Lowest slope ($T_3$) $\\implies$ highest resistance $R_3$.\nFor metals, resistance increases with temperature ($R \\propto T$).\nTherefore: $R_1 < R_2 < R_3 \\implies T_1 < T_2 < T_3$.',
      explanationBn: '$I-V$ লেখচিত্রে নতি $= \\frac{I}{V} = \\frac{1}{R}$।\nনতি বেশি হলে রোধ কম হয় ($R_1 < R_2 < R_3$)।\nধাতুর রোধ উষ্ণতা বৃদ্ধির সাথে বৃদ্ধি পায় ($R \\propto T$)।\nঅতএব $T_1 < T_2 < T_3$।',
      formula: '\\text{Slope} = \\frac{1}{R} \\implies T_1 < T_2 < T_3',
      simulationType: 'DRIFT_AND_RESISTANCE',
      simulationParams: JSON.stringify({ mode: 'IV_TEMP' }),
      isPublished: true,
    },
    // --- Q30 ---
    {
      code: 'WB12-PYQ-Q030',
      chapterId: ch2.id,
      difficulty: 'MEDIUM',
      questionEn: 'Two cells A and B are connected in parallel. Their EMFs are $3\\text{ V}$ and $2\\text{ V}$ respectively, and their internal resistances are $0.2\\,\\Omega$ and $0.3\\,\\Omega$ respectively. The equivalent EMF of the combination is:',
      questionBn: 'চিত্রে A এবং B দুটি তড়িৎকোষ সমান্তরালে যুক্ত। ওদের তড়িৎচালক বল যথাক্রমে 3 volt এবং 2 volt। অভ্যন্তরীণ রোধ যথাক্রমে $0.2\\,\\Omega$ এবং $0.3\\,\\Omega$। সমবায়টির তুল্য তড়িৎচালক বল হল—',
      optionA_En: '$5\\text{ volt}$',
      optionA_Bn: '$5\\text{ volt}$',
      optionB_En: '$1\\text{ volt}$',
      optionB_Bn: '$1\\text{ volt}$',
      optionC_En: '$2.4\\text{ volt}$',
      optionC_Bn: '$2.4\\text{ volt}$',
      optionD_En: '$2.6\\text{ volt}$',
      optionD_Bn: '$2.6\\text{ volt}$',
      correctOption: 'D',
      explanationEn: 'Equivalent EMF for two cells in parallel:\n$$E_{\\text{eq}} = \\frac{\\frac{E_1}{r_1} + \\frac{E_2}{r_2}}{\\frac{1}{r_1} + \\frac{1}{r_2}} = \\frac{\\frac{3}{0.2} + \\frac{2}{0.3}}{\\frac{1}{0.2} + \\frac{1}{0.3}} = \\frac{15 + \\frac{20}{3}}{5 + \\frac{10}{3}} = \\frac{\\frac{65}{3}}{\\frac{25}{3}} = \\frac{65}{25} = 2.6\\text{ V}$$',
      explanationBn: 'সমান্তরাল সমবায়ে তুল্য তড়িৎচালক বল:\n$$E_{\\text{eq}} = \\frac{\\frac{E_1}{r_1} + \\frac{E_2}{r_2}}{\\frac{1}{r_1} + \\frac{1}{r_2}} = \\frac{\\frac{3}{0.2} + \\frac{2}{0.3}}{\\frac{1}{0.2} + \\frac{1}{0.3}} = \\frac{65/3}{25/3} = 2.6\\text{ V}$$',
      formula: 'E_{\\text{eq}} = \\frac{\\frac{E_1}{r_1} + \\frac{E_2}{r_2}}{\\frac{1}{r_1} + \\frac{1}{r_2}} = 2.6\\text{ V}',
      simulationType: 'CIRCUIT_INSTRUMENTS',
      simulationParams: JSON.stringify({ mode: 'PARALLEL_CELLS' }),
      isPublished: true,
    },
    // --- Q31 ---
    {
      code: 'WB12-PYQ-Q031',
      chapterId: ch4.id,
      difficulty: 'MEDIUM',
      questionEn: 'In a transformer with 500 turns in the primary coil, the primary current is $4\\text{ A}$. If the input power is $1\\text{ kW}$, what number of turns in the secondary coil is required to obtain an output of $500\\text{ V}$?',
      questionBn: 'একটি ট্রান্সফরমারের 500 পাকের প্রাথমিক কুণ্ডলীতে প্রবাহ হল $4\\text{ A}$। ইনপুট ক্ষমতা $1\\text{ kW}$ হলে, গৌণ কুণ্ডলীর কত পাকসংখ্যার জন্য আউটপুট $500\\text{ V}$ পাওয়া যাবে?',
      optionA_En: '$1000$',
      optionA_Bn: '$1000$',
      optionB_En: '$400$',
      optionB_Bn: '$400$',
      optionC_En: '$2000$',
      optionC_Bn: '$2000$',
      optionD_En: '$1500$',
      optionD_Bn: '$1500$',
      correctOption: 'A',
      explanationEn: 'Primary voltage: $V_p = \\frac{P_{\\text{in}}}{I_p} = \\frac{1000\\text{ W}}{4\\text{ A}} = 250\\text{ V}$.\nSecondary voltage $V_s = 500\\text{ V}$, and $N_p = 500$.\nTransformer turns ratio:\n$$\\frac{V_s}{V_p} = \\frac{N_s}{N_p} \\implies \\frac{500}{250} = \\frac{N_s}{500} \\implies 2 = \\frac{N_s}{500} \\implies N_s = 1000\\text{ turns}$$',
      explanationBn: 'প্রাথমিক ভোল্টেজ $V_p = \\frac{1000\\text{ W}}{4\\text{ A}} = 250\\text{ V}$।\nগৌণ ভোল্টেজ $V_s = 500\\text{ V}$, প্রাথমিক পাকসংখ্যা $N_p = 500$।\n$$\\frac{N_s}{N_p} = \\frac{V_s}{V_p} \\implies \\frac{N_s}{500} = \\frac{500}{250} = 2 \\implies N_s = 1000$$',
      formula: '\\frac{V_s}{V_p} = \\frac{N_s}{N_p} \\implies N_s = 1000',
      simulationType: 'AC_CIRCUITS_TRANSFORMER',
      simulationParams: JSON.stringify({ mode: 'TRANSFORMER' }),
      isPublished: true,
    },
    // --- Q32 ---
    {
      code: 'WB12-PYQ-Q032',
      chapterId: ch4.id,
      difficulty: 'MEDIUM',
      questionEn: 'For a half-cycle of an AC circuit, the ratio of the rms value to the average value of alternating current is:',
      questionBn: 'ac বর্তনীর অর্ধচক্রের জন্য তড়িৎপ্রবাহের rms মান ও গড় মানের অনুপাত হল—',
      optionA_En: '$\\sqrt{2} : \\pi$',
      optionA_Bn: '$\\sqrt{2} : \\pi$',
      optionB_En: '$\\sqrt{2} : 1$',
      optionB_Bn: '$\\sqrt{2} : 1$',
      optionC_En: '$2\\sqrt{2} : \\pi$',
      optionC_Bn: '$2\\sqrt{2} : \\pi$',
      optionD_En: '$\\pi : 2\\sqrt{2}$',
      optionD_Bn: '$\\pi : 2\\sqrt{2}$',
      correctOption: 'D',
      explanationEn: 'RMS value of alternating current: $I_{\\text{rms}} = \\frac{I_0}{\\sqrt{2}}$.\nAverage value over a positive half-cycle: $I_{\\text{avg}} = \\frac{2 I_0}{\\pi}$.\nRatio:\n$$\\frac{I_{\\text{rms}}}{I_{\\text{avg}}} = \\frac{I_0 / \\sqrt{2}}{2 I_0 / \\pi} = \\frac{\\pi}{2\\sqrt{2}} = \\pi : 2\\sqrt{2}$$',
      explanationBn: 'rms মান $I_{\\text{rms}} = \\frac{I_0}{\\sqrt{2}}$।\nঅর্ধচক্রে গড় মান $I_{\\text{avg}} = \\frac{2I_0}{\\pi}$।\nঅনুপাত: $\\frac{I_{\\text{rms}}}{I_{\\text{avg}}} = \\frac{I_0/\\sqrt{2}}{2I_0/\\pi} = \\frac{\\pi}{2\\sqrt{2}} = \\pi : 2\\sqrt{2}$।',
      formula: '\\frac{I_{\\text{rms}}}{I_{\\text{avg}}} = \\frac{\\pi}{2\\sqrt{2}}',
      simulationType: 'AC_CIRCUITS_TRANSFORMER',
      isPublished: true,
    },
    // --- Q33 ---
    {
      code: 'WB12-PYQ-Q033',
      chapterId: ch4.id,
      difficulty: 'EASY',
      questionEn: 'The condition to obtain maximum current in a series LCR circuit is:',
      questionBn: 'একটি LCR শ্রেণি বর্তনীতে সর্বোচ্চ প্রবাহ পাওয়ার শর্ত হল—',
      optionA_En: '$X_L = 0$',
      optionA_Bn: '$X_L = 0$',
      optionB_En: '$X_C = 0$',
      optionB_Bn: '$X_C = 0$',
      optionC_En: '$X_L = X_C$',
      optionC_Bn: '$X_L = X_C$',
      optionD_En: '$R = X_L - X_C$',
      optionD_Bn: '$R = X_L - X_C$',
      correctOption: 'C',
      explanationEn: 'In a series LCR circuit, total impedance is $Z = \\sqrt{R^2 + (X_L - X_C)^2}$.\nCurrent $I = \\frac{V}{Z}$ is maximum when impedance $Z$ is minimum ($Z = R$), which happens at electrical resonance where $X_L = X_C$.',
      explanationBn: 'শ্রেণি LCR বর্তনীর প্রতিবাধা $Z = \\sqrt{R^2 + (X_L - X_C)^2}$।\nপ্রবাহ $I = V/Z$ সর্বোচ্চ হবে যখন $Z$ সর্বনিম্ন ($Z = R$) হবে, অর্থাৎ অনুনাদের শর্তে $X_L = X_C$।',
      formula: 'X_L = X_C',
      simulationType: 'AC_CIRCUITS_TRANSFORMER',
      simulationParams: JSON.stringify({ mode: 'LCR_RESONANCE' }),
      isPublished: true,
    },
    // --- Q34 ---
    {
      code: 'WB12-PYQ-Q034',
      chapterId: ch4.id,
      difficulty: 'EASY',
      questionEn: 'The equation of an alternating EMF is $E = 220 \\sin\\left(100\\pi t - \\frac{\\pi}{15}\\right)\\text{ V}$, where $t$ is in seconds. Its rms value and frequency are respectively:',
      questionBn: 'একটি পরিবর্তী তড়িৎচালক বলের সমীকরণ $E = 220 \\sin\\left(100\\pi t - \\frac{\\pi}{15}\\right)\\text{ V}$, যেখানে $t$ সেকেন্ড এককে প্রকাশিত। এর rms মান ও কম্পাঙ্ক যথাক্রমে হয়—',
      optionA_En: '$\\dfrac{220}{\\sqrt{2}}\\text{ V}, 50\\text{ Hz}$',
      optionA_Bn: '$\\dfrac{220}{\\sqrt{2}}\\text{ V}, 50\\text{ Hz}$',
      optionB_En: '$220\\text{ V}, 50\\text{ Hz}$',
      optionB_Bn: '$220\\text{ V}, 50\\text{ Hz}$',
      optionC_En: '$\\dfrac{220}{\\sqrt{2}}\\text{ V}, 100\\text{ Hz}$',
      optionC_Bn: '$\\dfrac{220}{\\sqrt{2}}\\text{ V}, 100\\text{ Hz}$',
      optionD_En: '$220\\sqrt{2}\\text{ V}, 50\\text{ Hz}$',
      optionD_Bn: '$220\\sqrt{2}\\text{ V}, 50\\text{ Hz}$',
      correctOption: 'A',
      explanationEn: 'Comparing with $E = E_0 \\sin(\\omega t - \\phi)$:\n- Peak EMF $E_0 = 220\\text{ V} \\implies E_{\\text{rms}} = \\frac{E_0}{\\sqrt{2}} = \\frac{220}{\\sqrt{2}}\\text{ V}$.\n- Angular frequency $\\omega = 100\\pi\\text{ rad/s} \\implies 2\\pi f = 100\\pi \\implies f = 50\\text{ Hz}$.',
      explanationBn: 'শীর্ষমান $E_0 = 220\\text{ V} \\implies E_{\\text{rms}} = \\frac{220}{\\sqrt{2}}\\text{ V}$।\nকৌণিক কম্পাঙ্ক $\\omega = 100\\pi \\implies 2\\pi f = 100\\pi \\implies f = 50\\text{ Hz}$।',
      formula: 'E_{\\text{rms}} = \\frac{E_0}{\\sqrt{2}}, \\quad f = \\frac{\\omega}{2\\pi} = 50\\text{ Hz}',
      simulationType: 'AC_CIRCUITS_TRANSFORMER',
      isPublished: true,
    },
    // --- Q35 ---
    {
      code: 'WB12-PYQ-Q035',
      chapterId: ch4.id,
      difficulty: 'MEDIUM',
      questionEn: 'The magnetic flux in a circuit of resistance $7\\,\\Omega$ is given by $\\phi = 6t^2 - 5t + 4\\text{ Wb}$. The induced current at time $t = 1\\text{ s}$ will be:',
      questionBn: '$7\\,\\Omega$ রোধের একটি বর্তনীতে চৌম্বক প্রবাহের রাশিমালা $\\phi = 6t^2 - 5t + 4$ হলে $t = 1\\text{ s}$-এ আবিষ্ট তড়িৎপ্রবাহমাত্রা হবে—',
      optionA_En: '$1.2\\text{ A}$',
      optionA_Bn: '$1.2\\text{ A}$',
      optionB_En: '$0.8\\text{ A}$',
      optionB_Bn: '$0.8\\text{ A}$',
      optionC_En: '$0.5\\text{ A}$',
      optionC_Bn: '$0.5\\text{ A}$',
      optionD_En: '$1\\text{ A}$',
      optionD_Bn: '$1\\text{ A}$',
      correctOption: 'D',
      explanationEn: 'Induced EMF magnitude by Faraday\'s law:\n$$|\\mathcal{E}| = \\left|\\frac{d\\phi}{dt}\\right| = \\frac{d}{dt}(6t^2 - 5t + 4) = 12t - 5$$\nAt $t = 1\\text{ s}$: $|\\mathcal{E}| = 12(1) - 5 = 7\\text{ V}$.\nInduced current:\n$$I = \\frac{|\\mathcal{E}|}{R} = \\frac{7\\text{ V}}{7\\,\\Omega} = 1\\text{ A}$$',
      explanationBn: 'ফ্যারাডের সূত্র অনুযায়ী আবিষ্ট তড়িচ্চালক বল:\n$$|\\mathcal{E}| = \\left|\\frac{d\\phi}{dt}\\right| = 12t - 5$$\n$t = 1\\text{ s}$-এ $|\\mathcal{E}| = 12(1) - 5 = 7\\text{ V}$।\nআবিষ্ট প্রবাহ $I = \\frac{|\\mathcal{E}|}{R} = \\frac{7\\text{ V}}{7\\,\\Omega} = 1\\text{ A}$।',
      formula: 'I = \\frac{|d\\phi/dt|}{R} = 1\\text{ A}',
      simulationType: 'AC_CIRCUITS_TRANSFORMER',
      simulationParams: JSON.stringify({ mode: 'FARADAY_FLUX' }),
      isPublished: true,
    },
  ];

  for (const q of questionsData) {
    await prisma.question.upsert({
      where: { code: q.code },
      update: q,
      create: q,
    });
  }

  console.log(`✅ Successfully seeded ALL ${questionsData.length} authentic bilingual physics questions with interactive simulations!`);

  // 4. Create Practice Mock Test for Semester 3
  const allQuestions = await prisma.question.findMany({
    orderBy: { code: 'asc' },
  });

  const test = await prisma.test.upsert({
    where: { id: 'test-wb12-sem3-full' },
    update: {
      totalMarks: allQuestions.length,
    },
    create: {
      id: 'test-wb12-sem3-full',
      chapterId: ch1.id,
      titleEn: 'Class 12 Physics — Semester 3 Full PYQ Mock Test (35 Questions)',
      titleBn: 'দ্বাদশ শ্রেণি পদার্থবিদ্যা — সেমিস্টার ৩ সম্পূর্ণ বিগত বছরের প্রশ্নপত্র (৩৫টি প্রশ্ন)',
      durationMinutes: 75,
      totalMarks: allQuestions.length,
      testQuestions: {
        create: allQuestions.map((q, idx) => ({
          questionId: q.id,
          orderIndex: idx,
        })),
      },
    },
  });

  console.log('✅ Created Full Semester 3 Practice Mock Test:', test.titleEn);
  console.log('🚀 Database seed finished successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
